# Pengaturan build dasar
[build]
  # Direktori tempat fungsi serverless Anda berada.
  functions = "netlify/functions"
  # Direktori yang akan di-publish (berisi index.html).
  publish = "."

  # Menetapkan variabel lingkungan untuk build
  [build.environment]
    # Menentukan versi Python yang akan digunakan.
    # Ini membantu memastikan konsistensi lingkungan build dan kompatibilitas paket.
    PYTHON_VERSION = "3.11"

# Pengaturan untuk SEMUA fungsi dalam proyek.
# Menggunakan wildcard "*" adalah cara yang benar untuk menerapkan
# pengaturan ke setiap fungsi di direktori 'functions'.
[functions."*"]
  # Menaikkan batas waktu timeout (dalam detik).
  # Ini penting untuk fungsi yang memproses file, karena bisa memakan waktu
  # lebih dari default 10 detik.
  timeout = 30
